### ISSUE TITLE
关于debug与release建议

### ISSUE THREAD

**Issue by chengxinping** [DingProg/NetworkCaptureSelf#1]
目前咱们的库是debug包就显示入口，release包不显示，能否考虑这个显示规则自己在application里面配置，因为一般发给QA测试也得发release包测试混淆

**Comment by chengxinping** [comment]
就是说希望能通过Java代码设置 而不是依赖不同的包

**Comment by DingProg** [comment]
>> 目前咱们的库是debug包就显示入口，release包不显示，能否考虑这个显示规则自己在application里面配置，因为一般发给QA测试也得发release包测试混淆

# 您好，已经收到您的反馈，这里有两个建议先参考一下。
##  1. Release包
Release包中是一个空壳，几乎不含任何Debug相关的代码，我们项目对debug资源是完全隔离的，这样的话Release包就完全不会带来任何包体积增加和，和风险代码。

###  我们采用的方式是，3个buildType ，其中
- develop 是开发分支下的，不混淆，加快开发速度
- debug 给QA使用的，可以正常切换环境，混淆配置，去除资源配置等完全和线上一致
- release 发包用的，仅仅是关闭debug下的资源

### 最后如下方式依赖：
```java
    releaseApi 'com.xxxx.xxxx:tech-develop:'+rootProject.tech_develop_release
    developApi 'com.xxxx.xxxxx-develop:'+rootProject.tech_develop
    debugApi 'com.xxxx.xxxx:tech-develop:'+rootProject.tech_develop
```


## 2. 仅仅提供一个依赖的话
技术实现中 ，创建快捷方式是通过Manifest注册的形势
```xml
<!-- 用于提供 Context debug包没什么问题 -->
 <provider
            android:authorities="com.ding.library"
            android:name=".internal.utils.CaptureContext"/>

        <activity
            android:name="com.ding.library.internal.ui.CaptureInfoActivity"
           android:configChanges="keyboardHidden|orientation|screenSize|smallestScreenSize|locale"
            android:launchMode="singleInstance"
            android:screenOrientation="portrait"
            android:theme="@style/AppTheme.NoActionBar" />

        <activity-alias
            android:label="抓包入口"
            android:name="CaptureInfoActivity"
            android:targetActivity="com.ding.library.internal.ui.CaptureInfoActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity-alias>
```
如果改为一个依赖的话，需要增加 APP安装快捷方式的权限，
```xml
<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>
```
会直接带入到release包中，很多APP对权限有严格的把控，所以这种方式也是有代价的。

# 最后
以上建议仅供交流，如果的确有需要，建议fork代码，把manifest中快捷方式的注册去掉。
直接该用代码创建快捷方式
```java
Intent addIntent=new Intent("com.android.launcher.action.INSTALL_SHORTCUT");
Parcelable icon=Intent.ShortcutIconResource.fromContext(CaptureInfoActivity.this,R.drawable.icon);
Intent myIntent=new Intent(context,CaptureInfoActivity.class);
addIntent.putExtra(Intent.EXTRA_SHORTCUT_NAME, "抓包入口");
addIntent.putExtra(Intent.EXTRA_SHORTCUT_ICON_RESOURCE, icon);
addIntent.putExtra(Intent.EXTRA_SHORTCUT_INTENT,myIntent);
sendBroadcast(addIntent);
```

如果有问题，欢迎一起交流！

**Comment by chengxinping** [comment]
> > > 目前咱们的库是debug包就显示入口，release包不显示，能否考虑这个显示规则自己在application里面配置，因为一般发给QA测试也得发release包测试混淆
> 
> # 您好，已经收到您的反馈，这里有两个建议先参考一下。
> ## 1. Release包
> Release包中是一个空壳，几乎不含任何Debug相关的代码，我们项目对debug资源是完全隔离的，这样的话Release包就完全不会带来任何包体积增加和，和风险代码。
> 
> ### 我们采用的方式是，3个buildType ，其中
> * develop 是开发分支下的，不混淆，加快开发速度
> * debug 给QA使用的，可以正常切换环境，混淆配置，去除资源配置等完全和线上一致
> * release 发包用的，仅仅是关闭debug下的资源
> 
> ### 最后如下方式依赖：
> ```java
>     releaseApi 'com.xxxx.xxxx:tech-develop:'+rootProject.tech_develop_release
>     developApi 'com.xxxx.xxxxx-develop:'+rootProject.tech_develop
>     debugApi 'com.xxxx.xxxx:tech-develop:'+rootProject.tech_develop
> ```
> 
> ## 2. 仅仅提供一个依赖的话
> 技术实现中 ，创建快捷方式是通过Manifest注册的形势
> 
> ```
> 
>  <provider
>             android:authorities="com.ding.library"
>             android:name=".internal.utils.CaptureContext"/>
> 
>         <activity
>             android:name="com.ding.library.internal.ui.CaptureInfoActivity"
>            android:configChanges="keyboardHidden|orientation|screenSize|smallestScreenSize|locale"
>             android:launchMode="singleInstance"
>             android:screenOrientation="portrait"
>             android:theme="@style/AppTheme.NoActionBar" />
> 
>         <activity-alias
>             android:label="抓包入口"
>             android:name="CaptureInfoActivity"
>             android:targetActivity="com.ding.library.internal.ui.CaptureInfoActivity">
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
>         </activity-alias>
> ```
> 
> 如果改为一个依赖的话，需要增加 APP安装快捷方式的权限，
> 
> ```
> <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>
> ```
> 
> 会直接带入到release包中，很多APP对权限有严格的把控，所以这种方式也是有代价的。
> 
> # 最后
> 以上建议仅供交流，如果的确有需要，建议fork代码，把manifest中快捷方式的注册去掉。
> 直接该用代码创建快捷方式
> 
> ```java
> Intent addIntent=new Intent("com.android.launcher.action.INSTALL_SHORTCUT");
> Parcelable icon=Intent.ShortcutIconResource.fromContext(CaptureInfoActivity.this,R.drawable.icon);
> Intent myIntent=new Intent(context,CaptureInfoActivity.class);
> addIntent.putExtra(Intent.EXTRA_SHORTCUT_NAME, "抓包入口");
> addIntent.putExtra(Intent.EXTRA_SHORTCUT_ICON_RESOURCE, icon);
> addIntent.putExtra(Intent.EXTRA_SHORTCUT_INTENT,myIntent);
> sendBroadcast(addIntent);
> ```
> 
> 如果有问题，欢迎一起交流！

感谢您的回复 目前准备再配置一个develop的buildType
