### ISSUE TITLE
provider 的  authorities是不是应该设置为${applicationId}开头的

### ISSUE THREAD

**Issue by protectedMan** [DingProg/NetworkCaptureSelf#3]
我看这个项目的authorities是固定的，两个项目都有抓包入口，结果因为authorities相同只能同时装一个，建议这边改一下，拼接上应用包名防止重复
![image](https://user-images.githubusercontent.com/17565737/82777464-c9640800-9e80-11ea-9d0a-60fe6d11490a.png)

**Comment by DingProg** [comment]
一般使用了默认的方式抓包

# 建议自己fork一下代码，修改一下，我这里没有添加默认值,类似这种

重命名程序包后，可能会发生相同的错误。android:authorities从AndroidManifest.xml 检查string.xml中的值。
在string.xml中，该值应与清单中声明的​​包名称相同。

```
<provider
        android:authorities="@string/content_authority"
        android:name=".data.Provider"
        ... />

<string name="content_authority">com.whatever.android.sunshine.app</string>
```
