### ISSUE TITLE
抓包入口是要自己安装吗  我接入了没有看到抓包入口APK

### ISSUE THREAD

**Issue by VainAnts** [DingProg/NetworkCaptureSelf#4]
dependencies {
    debugImplementation 'com.github.DingProg.NetworkCaptureSelf:library:v1.0.2'
    releaseImplementation 'com.github.DingProg.NetworkCaptureSelf:library_no_op:v1.0.2'
}

**Comment by DingProg** [comment]
## 不需要，直接在桌面上就可以看见入口
