### ISSUE TITLE
有一个包没有内容

### ISSUE THREAD

**Issue by kenxiong0113** [DingProg/NetworkCaptureSelf#5]
releaseImplementation 'com.github.DingProg.NetworkCaptureSelf:library_no_op:v1.0.1'

这个是非必须依赖吧，里面都没有任何东西被使用

**Comment by DingProg** [comment]
> releaseImplementation 'com.github.DingProg.NetworkCaptureSelf:library_no_op:v1.0.1'
> 
> 这个是非必须依赖吧，里面都没有任何东西被使用

是的，这个是release依赖，一般情况下抓包只在debug下使用
